### ISSUE TITLE
Suggestion for left hand Vive touchpad movement

### ISSUE THREAD

**Issue by ronfar623** [Codes4Fun/RBDOOM-3-BFG#10]
First, thank you for this mod!  Finally bringing to reality what Oculus could not with the promise of Doom 3 BFG VR in the original Kickstarter.

I would like to suggest an option for touchpad movement where the left and right strafing quadrants are removed, and instead just the top and bottom of the touchpad are mapped to forward and back only.  Accidental lateral movement makes me quite ill, and I would much prefer to handle sideways movement by just pointing the Vive wand in the direction I want to go.  Thanks for your consideration!

**Comment by Codes4Fun** [comment]
I added a console command to disable strafing in the latest build.
vr_strafing 0
