### ISSUE TITLE
Vive controllers show in game but do not interact with opening menu

### ISSUE THREAD

**Issue by Boodgiejohnson** [Codes4Fun/RBDOOM-3-BFG#12]
Downloaded the mod today and my controllers show in game but are not working with any menus.

**Comment by Codes4Fun** [comment]
I never show your controllers in game so it is very likely you are in SteamVR dashboard, you need to press the system button below the touchpad, that will take you in and out of SteamVR dashboard.

**Comment by Boodgiejohnson** [comment]
actually, I realized that I am in a theater mode, which shows my controllers.  I start it from my desktop.

**Comment by Boodgiejohnson** [comment]
Why would I start in theater mode and how do I get out in into regular VR 3D?

**Comment by Codes4Fun** [comment]
Are you starting it from your desktop in VR?

Try it with VR off and then run it, it should automatically launch SteamVR when it starts.

You can also try adding it to your VR game library:

In the menu click Games > Add a Non-steam game to my library
Then find and add RBDoom3BFG.exe

Then in your library right click on the game and click properties
And check the checkbox to include in VR library.
Then you should be able to launch from SteamVR.
