### ISSUE TITLE
Missing DLLs - are the posted builds Release builds (not Debug)?

### ISSUE THREAD

**Issue by jordanManfrey** [Codes4Fun/RBDOOM-3-BFG#13]
I'm getting MSVCR110D.dll and openal32 dll errors when I try to start the new build (7).

**Comment by Codes4Fun** [comment]
Try the new file attached to the release and see if that fixes it, and because I am skeptical about it I also added a non-OpenAL release just in case the first one still doesn't work.

**Comment by jordanManfrey** [comment]
fallback non openal build works for me, I'm on Windows 10 x64.  Messed with reinstalling a bunch of VC++ redistributables but it didn't help

**Comment by Codes4Fun** [comment]
> fallback non openal build works for me, I'm on Windows 10 x64. Messed with reinstalling a bunch of VC++ redistributables but it didn't help

It is a debug DLL it really shouldn't depend on it. The weird thing is, I never needed that OpenAL32.dll before so it is very likely it is installed on my computer somewhere, and when I add the one that comes with RBDOOM-3-BFG it then complains about MSVCR110D.dll, so the one installed elsewhere on my system doesn't have that dependency :/

**Comment by Codes4Fun** [comment]
Okay, one last try. The new OpenAL32.dll is the one that works for me.

**Comment by jordanManfrey** [comment]
tried it, got a different error: "The application was unable to start correctly (0xc000007b)."

**Comment by Codes4Fun** [comment]
That sucks. Oh well, thanks for trying, I'll have to put this on a computer that doesn't have OpenAL installed and try to figure out if I can package it as a dll or if I have to ask people to install OpenAL :/

**Comment by Codes4Fun** [comment]
Looks like KozGit released his version which also has updated assets.

https://github.com/KozGit/DOOM3-BFG-RIFT/releases

He also has an OpenAL32.DLL, try his out and see if it runs better then mine does, if it works I will just copy his into my releases.

**Comment by jordanManfrey** [comment]
thanks, I'll give it a shot after work

Edit: v7.3 is working for me

**Comment by Codes4Fun** [comment]
I went ahead and updated my release with his OpenAL32.DLL since it has fixed another issue that I was able to reproduce:

https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/tag/1.1.0-openvr7
