### ISSUE TITLE
Default "walk" speed is way too fast.

### ISSUE THREAD

**Issue by Nagorak** [Codes4Fun/RBDOOM-3-BFG#14]
I realize this is probably how fast the marine actually moved in the normal flat-screen version, but when playing in VR the movement speed is way too fast.  It's obviously not actually a walking speed, instead it's like a fast jog.  On top of that, moving so fast is going to cause motion sickness in a large number of people.  I don't get motion sickness when moving at a slow speed, but as fast as you move in game it really turns my stomach.  

I suggest that the default walk speed be reduced to 1/3 of what it is.  A console command maybe could be added to adjust the speed, as well, but the default should be slower so it's easier on the average player.  Then those with cast iron stomachs could move the speed back up.

**Comment by kickymcassington** [comment]
I'm pretty sure the previous control's were defaulting to always run, there are options in the latest build (version 7) to customise the controls how you would like with several letting you walk before running. That walk speed may be a bit better for you.

**Comment by dborosev** [comment]
Having more variation between the low speed and high speed on the trackpad would solve this.

**Comment by kickymcassington** [comment]
looks like it's there in the latest version, the dev mentioned fixing the deadzone on the trackpad so now if you click close to the middle (at least in control mode 5 that i was using) you should move much slower. perhaps it could be refined a bit.

**Comment by vturecek** [comment]
I submitted a PR that lets you set movement speed with a console command: https://github.com/Codes4Fun/RBDOOM-3-BFG/pulls 

Reducing speed by 25% feels good to me.
