### ISSUE TITLE
Low memory error

### ISSUE THREAD

**Issue by duig0** [Codes4Fun/RBDOOM-3-BFG#15]
Hiya.

Great work, that is, looks great on youtube and such.

Unfortunately I cannot get it to run for more than a few momwnts before it crashes with a "low memory warning" or a "memory could not be read" error.

I can run the base game without issue.
I cab run steamvr without issue...but for some reason....when both are running the game lags and crashes.

I have 8 gigs of ram (50% +- in use according to task manager) 
Intel i7 processor
And intel intergrated graphics 

It is however the first time I have ever encountered such an error.

Any help or advice would be greatly appreaciated.

I have tried increasing and decreasing vram, I ran a disk check and also the sfc /scannow command prompt and could find no errors.

Thank  you in advance

**Comment by Codes4Fun** [comment]
I'm not seeing those error messages in the game code, maybe they are coming from windows. What version of windows are you running?

Are you running build 7? If you are, does this happen with both exes?

The game for me, looking at the Task Manager "Commit Size" I am seeing:
RBDoom3BFG.exe 1.3GB
Steam.exe 363MB
vrdashboard.exe 139MB
vrmonitor.exe 71MB
vrcompositor.exe 54MB
vrserver.exe 22MB

**Comment by duig0** [comment]
Hi

Im running windows 10 and yes the errors are from windows.

I have tried both build 6 and 7.

Thanks for your help :-)
