### ISSUE TITLE
Thanks for reverting left touchpad change and opening an issue tracker. Possible control refinement?

### ISSUE THREAD

**Issue by kickymcassington** [Codes4Fun/RBDOOM-3-BFG#2]
Like the subject says thanks again :)

One way to further improve the left touchpad control would be to copy more of Onwards system. They require not only contact with the touchpad to move but also clicking in on the touchpad to start movement, holding to continue walking and double click and hold for running.

If it's not too difficult I'd love to see this as an option for those that prefer it.
Also if issues isn't the right place for this kind of request just let me know :)
-Kicky

**Comment by Codes4Fun** [comment]
That is interesting, I'll have to try it out, and make it an option.

**Comment by sc0rch** [comment]
I'm always trying to click the touchpad to start movement (v4 of mod).
I will try the v6 version on next week.

**Comment by kickymcassington** [comment]
The updated Version 7 looks like it has exactly what I was looking for with vr_moveMode 5 for "click walk & double click run" I'll give it a try in a couple hours and report back!

**Comment by kickymcassington** [comment]
That was exactly what i was asking for, the touchpad movement feels perfect with mode 5, thanks for making it an option! feel free to close this one off now.

**Comment by Codes4Fun** [comment]
Cool :)
