### ISSUE TITLE
Clip or Fade Scene when player's head intersects geometry

### ISSUE THREAD

**Issue by druidsbane** [Codes4Fun/RBDOOM-3-BFG#24]
Pushing the player back causes unnecessary nausea.

**Comment by Nagorak** [comment]
It's been posted before, but I think something really needs to be done about this.  Our bounding box (?) is way too large.  When moving around I find myself getting hooked on pillars and stuff.  All this stuff adds up over time to worse motion sickness.

**Comment by Codes4Fun** [comment]
I've implemented something in the latest release for this.
