### ISSUE TITLE
Custom Maps!

### ISSUE THREAD

**Issue by Lelgia** [Codes4Fun/RBDOOM-3-BFG#27]
You are my Hero! I finished the main campaign and i am going very fast through the expansions. I am worried. I am addicted and I definetly want more. Doom 3 in VR is a blast, I think is better suited for VR than the recent DOOM because it's slow paced. I searched through all the internet and I horribly found out that most of the old custom maps are not compatible with the Bfg edition except for 4 maps that I found here that are adapted for the bfg version http://www.kot-in-action.com/forum/viewtopic.php?f=28&t=4436&sid=f45fb1420d4f09d8ffcedb99e81aba6e But I am unable to run them. I press the "\" and the console pops out but the "map" command doesn't work, I am a noob in this kind of things. What I am doing wrong?. Tell me there is a way !Help a poor soon unemployed space marine!

**Comment by Codes4Fun** [comment]
I got omega research to load but it seems broken (missing geometry), not sure what the official way you are supposed to use these maps but the way I was able to get omega research to load is to unzip the file, you end up with an omega_research directory. Copy the contents (def, generated, maps, etc) into your base directory, then to load it using the command:

map omegalabs/omega1

Its worth pointing out that the map command automatically appends "maps/" to the front.

**Comment by Codes4Fun** [comment]
Note, this is kind of dangerous, I found myself unable to play any normal doom levels after adding the new map data, until I cleaned by base directory of the map and a generated folder.
