### ISSUE TITLE
Stuck inside the VR room. 

### ISSUE THREAD

**Issue by Xyntro** [Codes4Fun/RBDOOM-3-BFG#30]
Hey guys, 

I followed the guide but somehow when I launch doom3 I only hear the sound through my vive but not the  visuals, I keep standing in the VR room.
I have no clue what I did wrong. Thx in advance.

**Comment by Codes4Fun** [comment]
I think someone on reddit had a similar problem:

https://www.reddit.com/r/Vive/comments/5emnpa/doom_3_vr_stuck_in_vr_home/

His solution:

> (It) was Nvidia assigning integrated graphics to the R3doom executable. I changed it in the nvidia control panel under 3d settings by adding the executable and forcing it to nvidia graphics and it is all showing up happy again.
