### ISSUE TITLE
Controller vibration get stuck

### ISSUE THREAD

**Issue by ecaginicolau** [Codes4Fun/RBDOOM-3-BFG#31]
Sometimes the vibration caused by a weapon won't stop by itself.
An easy way to reproduce it is to use Sarge's shotgun, it happens almost 100% of the time.
The only way I found to stop the vibration is to shoot a few bullets from the machine gun.

**Comment by Codes4Fun** [comment]
I am not able to reproduce this with either the normal shotgun or the double barrel shotgun (I'm not sure what is "Sarge's shotgun").

What area are you in when this occurs? There could be a subtle environmental vibration, and that could somehow be enhanced by the last intensive vibration (like a shotgun). You can also attach the save game files (game.details, gamedata.save, gamedata.strings) if that would be easier.

Is it an intense vibration or a subtle one?

Is this strictly the right controller or happens to both controllers?

Do you see anything in the console, like "right controller no pose" around the same time this occurs?

Are you using SteamVR beta?

**Comment by ecaginicolau** [comment]
Yes it was the double barrel shothun
I tried to reproduice the error and get you a save but now it's working !

Maybe an issue on my side? I think it was only the right controller and quite intensive.

Sorry

**Comment by ecaginicolau** [comment]
Ok I was able to reproduce it after some time. 
I do have the message "right controller no pose" in the console. I tried to exit and restart the game but it's still here. Each time I shoot with the shotgun the vibration get stuck until I use another weapon like the machine gun.

I'm not sure if my save can help you but here it is:

[GAME-doom3_8.zip](https://github.com/Codes4Fun/RBDOOM-3-BFG/files/614909/GAME-doom3_8.zip)

**Comment by ecaginicolau** [comment]
It happened after I've used the artefact, maybe it's related to the artefact and not the double barrel shotgun

**Comment by Codes4Fun** [comment]
Yes, I could reproduce with the shotgun after using the artefact, and I found a fixed the bug.

Also discovered I can't load saved games from a different language :/

But thanks a lot for your help!

**Comment by Codes4Fun** [comment]
New release build has the fix!
