### ISSUE TITLE
Grabber Physics Gun Intense Visual Distortion

### ISSUE THREAD

**Issue by Erare** [Codes4Fun/RBDOOM-3-BFG#32]
Using the grabber causes an intense distortion effect that takes over the whole screen.  While kind of neat, it makes the weapon unusable in its current state.

r_skipPostProcess doesn't effect it, neither does g_skipvieweffects or
r_skipAmbient or r_skipNewAmbient.

I've been digging around through weapon config scripts and a few other things, the effect is called FullscreenFX_Warp and this line can be found in playerview.h and playerview.cpp, among other places.

And here is a mod that managed to remove the warp effect, although I can't figure out how.
http://www.moddb.com/mods/gunmans-mod-105

**Comment by Codes4Fun** [comment]
Try in the console:
player_allowScreenFXInStereo 0

Unfortunately it looks like this is not one that is saved in the config file for some reason, so you will have to do it every time you restart the game.

I have yet to comb through all FX and either fix or remove them.

**Comment by Erare** [comment]
Ahh perfect, this will do for now.  I appreciate it!

**Comment by Codes4Fun** [comment]
New release build disables the warp effect.
