### ISSUE TITLE
Not working at all...

### ISSUE THREAD

**Issue by Alby90** [Codes4Fun/RBDOOM-3-BFG#34]
Seems to me that i am the only one to have this issue. (the headset is the Vive)
-I put all the files in the game root directory.
-Start Steam VR.
-Start the game with the RBDoom3BFG .exe

The game start in windowed mode but nothing happen in the Vive. 
What could be the cause?

**Comment by Codes4Fun** [comment]
It may be the same as issue #30, and I think someone on reddit had a similar problem:

https://www.reddit.com/r/Vive/comments/5emnpa/doom_3_vr_stuck_in_vr_home/

His solution:

> (It) was Nvidia assigning integrated graphics to the R3doom executable. I changed it in the nvidia control panel under 3d settings by adding the executable and forcing it to nvidia graphics and it is all showing up happy again.

**Comment by Alby90** [comment]
Mhhh....he has a Intel Graphic on the CPU and the nVidia GPU. 
I have a nVidia GTX 980 and a AMD FX-8350 with no integrated graphic that can cause problem.

**Comment by Codes4Fun** [comment]
Out of curiousity does SteamVR say in red "(unresponsive)"?

**Comment by Alby90** [comment]
No. All is working like always. 
I can even open a new game for the vive with no problem even if Doom 3 is on.

**Comment by StigsRedneckCousin** [comment]
I have the same issue right now. I'm also running a GTX980 but with i5-4690k.

**Comment by Codes4Fun** [comment]
If you exit both SteamVR and Steam, and then try running the game, does the game launch SteamVR?

You can also try adding the game to SteamVR by going into the Game menu and selecting "Add a Non-Steam Game to my Library", and then selecting the exe, and then when it is in your library, right click on it and select "Properties" from there you can check the box "include in VR library" and then try launching it from within SteamVR.

**Comment by StigsRedneckCousin** [comment]
Just tried launching it alone after a fresh reboot and steam closed. Doesn't bring up steamVR when I launch the exe from the folder. 

Tried adding as a non steam game like you suggested and it still just came up on the monitor.

**Comment by Codes4Fun** [comment]
> Just tried launching it alone after a fresh reboot and steam closed. Doesn't bring up steamVR when I launch the exe from the folder.

This is really strange!

In windows explorer, go to %userprofile%\Saved Games\id Software\RBDOOM 3 BFG\base and edit the D3BFGVRConfig.cfg file and add "set logFile 2" at the bottom, then run the game, this should create a file in the same folder called "qconsole.log" you can attach that here and/or look at it and let me know if there is a line "VR initialization failed: " or "VR compositor not present."
