### ISSUE TITLE
Infinite Flashlight

### ISSUE THREAD

**Issue by Erare** [Codes4Fun/RBDOOM-3-BFG#35]
I've been trying to find a way to make it so the flashlight does not run out of batteries.  It's kind of tedious using the grips to turn it back on all the time.

The only way I've been able to achieve something close is by breaking the flashlight with a weapon_flashlight script or def.  This puts the flashlight in a permanent on state, drains the battery to 0, but never quite turns off.  It stays in it's near dead flickering state, which is kinda nice but the flicker is bad.

Sorry, I know this isn't exactly a bug, I'm not sure where else to put this.  It's more of a VR QoL request.

Many thanks for your hard work, this mod is amazeballs!

**Comment by Erare** [comment]
IGNORE ME not useful info

**Comment by Codes4Fun** [comment]
I found these in the code, I don't know if they work but I do know they will not save (they need to reset on restart):

flashlight_batteryDrainTimeMS
flashlight_batteryChargeTimeMS
flashlight_minActivatePercent
flashlight_batteryFlickerPercent

I am not there yet, but at some point I want to make buttons bindable, so you can swap jump/flashlight/pda buttons, I also find the flashlight button a bit hard to press and you press it more than you do jump with the way the game is designed.

**Comment by Erare** [comment]
flashlight_batteryDrainTimeMS -1 works

Thanks again!!
