### ISSUE TITLE
No haptics felt

### ISSUE THREAD

**Issue by mamefan** [Codes4Fun/RBDOOM-3-BFG#36]
I've used v8, v7, and v6, and I'm not feeling any Vive controller vibrations. I'm using the hi-def mod, control method 2, and a smaller laser sight. I also deleted the barrel files and folders that were recommended to fix the elevator to level 2 issue. I hope my controller isn't broken.

**Comment by Codes4Fun** [comment]
Not sure if you are the same person on Steam but doesn't hurt to repeat it here, when you enter these in the console what do these return:

in_useJoystick

in_joystickRumble

**Comment by mamefan** [comment]
Yeah, I'm the same person. Just did it, and here's what I got:

in_useJoystick is: "0" default: "1"

in_joystickRumble is: "1" default: "1

After doing these commands, I tried the pistol, shotgun, and rifle and felt nothing. After that, I tried Space Pirate Trainer and confirmed that rumble works in both controllers with that game.

**Comment by Codes4Fun** [comment]
I don't know if it will work but you can try this:
in_useJoystick 1

I have an xbox controller connected to my PC and I think that sets that variable to 1, and that is why I am getting rumble.

I am going to make a fix that will allow for rumble to occur even if those console variables are not 1.

**Comment by mamefan** [comment]
in_useJoystick 1 fixed it! Thank you! How can I contribute to you?

**Comment by Codes4Fun** [comment]
> How can I contribute to you?

You already have by verifying that fixed it :)

**Comment by Codes4Fun** [comment]
New release build has a change that does haptics irregardless of what in_useJoystick is.
