### ISSUE TITLE
Crashes while crouching

### ISSUE THREAD

**Issue by plaidpants** [Codes4Fun/RBDOOM-3-BFG#37]
It's difficult to crouch enough with the rift as it has limited view down low, so when going under the floor just after extinguishing the fire and I happen bump my head up just around the bend the game crashes. I would also like a crouch button for the joystick controls so I can play without needing to get out of my chair.

**Comment by Codes4Fun** [comment]
If you want to play in a chair, play in seated mode:

vr_seated 1

With that you can use the crouch button, which I think is pressing in the left stick.

I'll need to try and reproduce that crash, it shouldn't crash. Maybe it lost tracking.

**Comment by plaidpants** [comment]
Thanks I'll try the vr_seated option.

**Comment by plaidpants** [comment]
still seemed to crash even with the vr_seated 1, seems to be related to the game trying to hide obscured areas, trying to put your head through a wall usually results in you being pushed back. In close quarters with tunnels this is not possible and you can get through ceilings and floors with your head. This seems to cause the crash. Could be a loss of tracking is related, lose tracking inside tunnel, re-established tracking outside of tunnel.

Also with vr_seated 1 you lose the head tracking for the weapon and flashlight. This mechanic was useful to reduce motion sickness, the flashlight illuminates a small field of view in front of the player only in the direction of gaze, similar to "eagle flight". I turned this off once I was able to get past the tunnel in this area, being careful to not poke my head outside of the tunnel.

**Comment by Codes4Fun** [comment]
In version 11 I added code to prevent your head from going through the top of crawl spaces, so I would think it would not crash anymore if that was the actual cause.
