### ISSUE TITLE
Character keeps moving after removing thumb from touchpad

### ISSUE THREAD

**Issue by Erare** [Codes4Fun/RBDOOM-3-BFG#38]
This happens quite often, where I'll be moving around with the default setup, and after I remove my thumb from the touchpad, my character keeps moving in the same direction at the same speed.  I can change direction by moving my hand and I can stop the movement by using the trackpad.

I've tried recalibrating my controllers and also switching hands, but the issue remains.  For now I use vr_movemode 3 to make sure I only move when I want to.

**Comment by Codes4Fun** [comment]
I've had this happen also but it was really rare and not easy to reproduce, and I tried adding logging to understand it but it almost seemed like openvr was still telling me the controller is being touched when it wasn't. It could be some issue that occurs when tracking is lost.

**Comment by ecaginicolau** [comment]
It happened to me too. I'll try to check it .
If we go to steam when it's happening and if we can still see the pad being touched in the 3D model (The default controller model shows the position of the finger on the pad) then it means it's an openvr bug. 
But if we don't see the pad being touched then  it means that there is a way to overcome this issue.

**Comment by veryjos** [comment]
I think this is an OpenVR bug. It happens in Penumbra: VR too. There might be a hueristic to work around it that engines like Unity implement on a lower level, because I haven't seen this happen in games other than native games. Might just be coincidence though, since I don't really play many VR games other than the ones I develop, which don't use engines like Unity.

**Comment by Codes4Fun** [comment]
It happened to me again and I verified this is definitely coming from SteamVR/OpenVR, I even managed to open up SteamVR dashboard and saw that it also thought I was touching when I wasn't.

**Comment by mamefan** [comment]
Does using click instead of touch help?

**Comment by Codes4Fun** [comment]
> Does using click instead of touch help?

If its a serious issue for someone, I would think they could get around it with hold to walk, click would still have the same problem since movement is still touch based.
