### ISSUE TITLE
Vive stays in workshop enviroment.

### ISSUE THREAD

**Issue by axelat** [Codes4Fun/RBDOOM-3-BFG#40]
Hi,

when I start RBDoom3BFG.exe the game starts in a desktop window but the vive still displays the standard workshop environment. 

Details:
I downloaded Doom3 BFG 2012 Edition in Steam, downloaded version 8 of https://github.com/Codes4Fun/RBDOOM-3-BFG/releases, extracted, copied to Doom3 BFG Folder, started SteamVR, started RBDoom3BFG.exe. The Game starts in a desktop Window, but the Vive still shows the workshop environment. I reinstalled the game several times, tried it with and without HiresTexPacks, Version 6, 7, and 8 of RBDoom and had no success so far. The Fallback exe shows the same behaviour. Each time before reinstalling the game I deleted the whole E:\steam\SteamApps\common\DOOM 3 BFG Edition folder.

From the steamvr system report:
SteamVR Version 2016-11-14 (1479163853) Steam: Public (beta) Tracking: lighthouse OS: Windows 10 (10.0.0.14393) Direct Mode Graphics: NVIDIA (376.09)
System Admin: Yes Async Reprojection: Enabled Allow Reprojection: Yes (Good) Force Reprojection: No (Good) Performance drops: / /2 /3 /4 / User IPD (m): 0.0688
Displays - Direct Mode Display 0: \.\DISPLAY6 2560x1080 @ (0, 0) NVIDIA GeForce GTX 1070 Primary Monitor 0: \.\DISPLAY6\Monitor0 Generic PnP Monitor
Display 1: NvAPI 2160x1200 @ (0, 0) NVIDIA Direct Mode

**Comment by Codes4Fun** [comment]
1. Do you happen to have integrated graphics? It doesn't look like you do but if you do, make sure in the Nvidia control panel, Manage 3D Settings, that it preferred graphics processor is set to use the Nvidia GPU, some people have had to manually set this for RBDoom3BFG.exe.
2. What is displayed in the window? Does it show both the left and right eyes?
3. Does head tracking work? Moving the HMD around does that update the view in the window?
4. Looking at SteamVR does it show the text "(unresponsive)" in red constantly? You should see "Connecting" and moments of "(unresponsive)" eventually followed by "Ready".

Somethings to try:

1. Try launching the game without SteamVR or Steam running, this should automatically launch SteamVR without Steam.
2. Try launching the game from SteamVR directly. Go to menu "Game" > "Add Non-Steam Game to my Library", then find the exe and add it, then right click the game in the library and select "Properties" and the checkbox "include in VR library", from there you can launch it from Steam.

**Comment by axelat** [comment]
1. Integrated Graphics is disabled in BIOS.
2. The Window shows the "normal" Game in a non stereoscopic view, it can be controlled by mouse and keyboard. I can start the campain and play several levels, the vive stays black or in workshop view (see below)
3. The tracking has no effect of the view in the window
4. SteamVR shows "Ready" all the time. Today after a clean uninstall, delete, and reinstall the Vive Screen went dark after Launching RBDomm3BFG.exe, SteamVR status was still ready. I tried to start campain mode within the window, but the HMD display stayed black.

Tried:
1) Quitting SteamVR and Steam, started RBDoom3BFG.exe did not launch Steam or SteamVR, just started in the usual Window.
2) Added Steam as a non Steam Game, edited properties finally changed something: the game is no displayed in the window stereoscopic, the head tracking has effect to the camera, also the controlers work. After starting the game the image is also displayed in the Vive Headset for about 1-2 seconds and then the display gets black again. Steam VR Status shows "unresponsive" in red text then!

**Comment by axelat** [comment]
After a restart of Windows it is working now. So the solution was: "Try launching the game from SteamVR directly. Go to menu "Game" > "Add Non-Steam Game to my Library", then find the exe and add it, then right click the game in the library and select "Properties" and the checkbox "include in VR library", from there you can launch it from Steam." thx a lot!
