### ISSUE TITLE
Floating screens ''swim''

### ISSUE THREAD

**Issue by dnhkng** [Codes4Fun/RBDOOM-3-BFG#41]
I've noticed that the loading screens "swim" around with head movement ever so slightly, enough to make things a bit uncomfortable. I only noticed it while I was near the chaperone bounds, as when they are on they are remain rock solid in place and you see the difference.

**Comment by Codes4Fun** [comment]
When you say "swim" are you referring maybe to aliasing issues, or do you mean in terms of head tracking?

If it is a tracking issue, does the same thing maybe if you were to press the SteamVR button and look at it's dashboard.

**Comment by dnhkng** [comment]
It looks like delayed tracking (200-500ms or so?), it seems to go away after the game finally loads. No big deal.

When I hit the SteamVR button, the image moves onto a virtual screen, so you cant see the delay anymore.

**Comment by Codes4Fun** [comment]
Oh, okay, I just notice you were talking about loading screens. So yeah those are not able to draw everyframe and without ATW or ASW, SteamVR won't update what is displayed with head tracking.

This is on my wish list for OpenVR, is that they gave me a way to give it something to display while the game is loading. It is also a pain about OpenGL is that you can't (as far as I know) load textures in one thread, while updating the screen in another.
