### ISSUE TITLE
Crash on startup, author troubleshoot not working

### ISSUE THREAD

**Issue by AyeJayy** [Codes4Fun/RBDOOM-3-BFG#42]
This is my crash log. I've tried the troubleshoots on his post and none of them work.
WARNING: file particles/chang.prt, line 4278: particle 'alphascrubsmoke' previously defined at particles/phrozo2_chang.prt:4248 WARNING: file particles/chang.prt, line 4376: particle 'recyc_pipedrip1' previously defined at particles/_phrozo2_chang.prt:4278 WARNING: file particles/chang.prt, line 4451: particle 'recyc_pipedrip2' previously defined at particles/_phrozo2_chang.prt:4376 WARNING: file particles/chang.prt, line 4482: particle 'delta5_crawlsmoke' previously defined at particles/_phrozo2_chang.prt:4451 WARNING: file particles/chang.prt, line 4510: particle 'commo_crawlsteam1' previously defined at particles/_phrozo2_chang.prt:4482 WARNING: file particles/chang.prt, line 4562: particle 'commo_steamduo' previously defined at particles/_phrozo2_chang.prt:4510 WARNING: file particles/chang.prt, line 4613: particle 'commo_crawlblast' previously defined at particles/_phrozo2_chang.prt:4562 WARNING: file particles/chang.prt, line 4664: particle 'commo_sawsteam' previously defined at particles/_phrozo2_chang.prt:4613 WARNING: file particles/chang.prt, line 4738: particle 'recyc_pipedrip10' previously defined at particles/_phrozo2_chang.prt:4664 WARNING: file particles/chang.prt, line 4790: particle 'recyc_chaindrip1' previously defined at particles/_phrozo2_chang.prt:4738 WARNING: file particles/chang.prt, line 4889: particle 'recyc_chaindrip2' previously defined at particles/_phrozo2_chang.prt:4790 WARNING: file particles/chang.prt, line 4987: particle 'recyc_hexdrip1' previously defined at particles/_phrozo2_chang.prt:4889 WARNING: file particles/chang.prt, line 5085: particle 'recyc_hexdrip2' previously defined at particles/_phrozo2_chang.prt:4987 WARNING: file particles/chang.prt, line 5183: particle 'recyc_hexdrip3' previously defined at particles/_phrozo2_chang.prt:5085 WARNING: file particles/chang.prt, line 5281: particle 'recyc_hexdrip4' previously defined at particles/_phrozo2_chang.prt:5183 WARNING: file particles/chang.prt, line 5332: particle 'delta2a_halonblast' previously defined at particles/_phrozo2_chang.prt:5281 WARNING: file particles/chang.prt, line 5383: particle 'delta2a_hosesmoke' previously defined at particles/_phrozo2_chang.prt:5332 WARNING: file particles/chang.prt, line 5412: particle 'delta2a_ventsteam2' previously defined at particles/_phrozo2_chang.prt:5383 WARNING: file particles/chang.prt, line 5441: particle 'delta2a_inhalersteam' previously defined at particles/_phrozo2_chang.prt:5412 WARNING: file particles/chang.prt, line 5492: particle 'delta2a_hallpanel' previously defined at particles/_phrozo2_chang.prt:5441 WARNING: file particles/chang.prt, line 5521: particle 'delta2a_telesmoke' previously defined at particles/_phrozo2_chang.prt:5492 WARNING: file particles/chang.prt, line 5619: particle 'monounderfire' previously defined at particles/_phrozo2_chang.prt:5521 WARNING: file particles/duffy.prt, line 68: particle 'flamejet' previously defined at particles/_phrozo2_duffy.prt:1 WARNING: file particles/duffy.prt, line 94: particle 'flamejetsmoke' previously defined at particles/_phrozo2_duffy.prt:68 WARNING: file particles/duffy.prt, line 140: particle 'lava1move' previously defined at particles/_phrozo2_duffy.prt:94 WARNING: file particles/duffy.prt, line 165: particle 'al2turkey' previously defined at particles/_phrozo2_duffy.prt:140 WARNING: file particles/duffy.prt, line 210: particle 'hugeexplosion' previously defined at particles/_phrozo2_duffy.prt:165 WARNING: file particles/duffy.prt, line 237: particle 'deconsteam' previously defined at particles/_phrozo2_duffy.prt:210 WARNING: file particles/duffy.prt, line 263: particle 'decompress' previously defined at particles/_phrozo2_duffy.prt:237 WARNING: file particles/duffy.prt, line 290: particle 'delta2a_teleportmachine' previously defined at particles/_phrozo2_duffy.prt:263 WARNING: file particles/duffy.prt, line 316: particle 'delta3_reddishsteam' previously defined at particles/_phrozo2_duffy.prt:290 WARNING: file particles/duffy.prt, line 368: particle 'flies' previously defined at particles/_phrozo2_duffy.prt:316 WARNING: file particles/duffy.prt, line 420: particle 'debristrail' previously defined at particles/_phrozo2_duffy.prt:368 WARNING: file particles/duffy.prt, line 446: particle 'spawnring' previously defined at particles/_phrozo2_duffy.prt:420 WARNING: file particles/duffy.prt, line 492: particle 'roaches' previously defined at particles/_phrozo2_duffy.prt:446 WARNING: file particles/duffy.prt, line 539: particle 'roachfountain' previously defined at particles/_phrozo2_duffy.prt:492 WARNING: file particles/duffy.prt, line 565: particle 'burnaway' previously defined at particles/_phrozo2_duffy.prt:539 WARNING: file particles/duffy.prt, line 591: particle 'plasmaprj' previously defined at particles/_phrozo2_duffy.prt:565 WARNING: file particles/duffy.prt, line 617: particle 'flowingblood' previously defined at particles/_phrozo2_duffy.prt:591 WARNING: file particles/duffy.prt, line 666: particle 'bodyburn' previously defined at particles/_phrozo2_duffy.prt:617 WARNING: file particles/duffy.prt, line 696: particle 'lava2move' previously defined at particles/_phrozo2_duffy.prt:666 WARNING: file particles/duffy.prt, line 723: particle 'caverns2_steam1' previously defined at particles/_phrozo2_duffy.prt:696 WARNING: file particles/duffy.prt, line 751: particle 'caverns2_smoke1' previously defined at particles/_phrozo2_duffy.prt:723 WARNING: file particles/duffy.prt, line 779: particle 'caverns2_arc1' previously defined at particles/_phrozo2_duffy.prt:751 WARNING: file particles/duffy.prt, line 805: particle 'caverns2_lamplight' previously defined at particles/_phrozo2_duffy.prt:779 WARNING: file particles/duffy.prt, line 833: particle 'caverns2_steam2' previously defined at particles/_phrozo2_duffy.prt:805 WARNING: file particles/duffy.prt, line 861: particle 'caverns2_smoke3' previously defined at particles/_phrozo2_duffy.prt:833 WARNING: file particles/duffy.prt, line 889: particle 'caverns2_redsteam' previously defined at particles/_phrozo2_duffy.prt:861 WARNING: file particles/duffy.prt, line 915: particle 'caverns2_blacksmoke' previously defined at particles/_phrozo2_duffy.prt:889 WARNING: file particles/duffy.prt, line 943: particle 'caverns2_eggthingies' previously defined at particles/_phrozo2_duffy.prt:915 WARNING: file particles/duffy.prt, line 971: particle 'caverns2_redsmoke' previously defined at particles/_phrozo2_duffy.prt:943 WARNING: file particles/duffy.prt, line 999: particle 'ceilingdust' previously defined at particles/_phrozo2_duffy.prt:971 WARNING: file particles/duffy.prt, line 1026: particle 'longceilingdust' previously defined at particles/_phrozo2_duffy.prt:999 WARNING: file particles/duffy.prt, line 1054: particle 'floordust' previously defined at particles/_phrozo2_duffy.prt:1026 WARNING: file particles/duffy.prt, line 1081: particle 'hose_condensation' previously defined at particles/_phrozo2_duffy.prt:1054 WARNING: file particles/duffy.prt, line 1107: particle 'bloodsplat' previously defined at particles/_phrozo2_duffy.prt:1081 WARNING: file particles/duffy.prt, line 1133: particle 'lightningball' previously defined at particles/_phrozo2_duffy.prt:1107 WARNING: file particles/duffy.prt, line 1159: particle 'bfgball' previously defined at particles/_phrozo2_duffy.prt:1133 WARNING: file particles/duffy.prt, line 1188: particle 'al3barrelsteam' previously defined at particles/_phrozo2_duffy.prt:1159 WARNING: file particles/duffy.prt, line 1218: particle 'bloodwound' previously defined at particles/_phrozo2_duffy.prt:1188 more than 256 warnings Preloading images... Writing generated/images/textures/decals/bulletglass1_d#0200.bimage: 64x64 Writing generated/images/textures/decals/bulletglass1_d#0200.bimage: 64x64 Writing generated/images/models/monsters/skeleton/skeleton01_d#0100.bimage: 512x512 Writing generated/images/models/monsters/skeleton/skeleton01_d#_0100.bimage: 512x512
00362 images preloaded ( or were already loaded ) in 5.6 seconds

00259 sounds preloaded in 0.0 seconds

--- Common Initialization Complete --- QA Timing IIS: 014655ms Added local user: RED Opening IP socket: localhost:27015 execing joy_righty.cfg execing joy_360_0.cfg NET: PartyToken is 6990 (seed = 82817) --------- Execute Map Change --------- Map: game/mars_city1 Loaded resource file maps/mars_city1.resources
--------- Game Map Shutdown ----------

24 msec to unload map
 5 msec to free assets
Preloading images...
02180 images preloaded ( or were already loaded ) in 29.3 seconds

WARNING: idSessionLocal::Pump was not called for 29 seconds idVertexBuffer::MapBuffer: failed Shutting down OpenGL subsystem ...wglMakeCurrent( NULL, NULL ): success ...deleting GL context: success ...releasing DC: success ...destroying window

**Comment by Codes4Fun** [comment]
I've not seen those warnings before, there may be something wrong with your data. Are you using this with DOOM 3 BFG edition? Is it from Steam or from somewhere else? If it is not from Steam it could possibly require a patch. Also did you install any other mods? If you did, try starting fresh by uninstalling and reinstalling and only copy over the contents of [RBDoom3BFG.1.1.0.OpenVR8.zip](https://github.com/Codes4Fun/RBDOOM-3-BFG/releases), and then make sure to delete old configuration data by deleting this folder if it exists: %userprofile%\Saved Games\id Software\RBDOOM 3 BFG

**Comment by AyeJayy** [comment]
I will reinstall it then. Other than the mod, I only installed the texture pack. I did download the game from steam, and it runs fine as long as I don't enter VR.
