### ISSUE TITLE
Where can I donate???

### ISSUE THREAD

**Issue by bhaal66** [Codes4Fun/RBDOOM-3-BFG#43]
Hello,

I´m new to Github, but I love your work with DOOM3-BFG-VR!! I would really like to donate some for your great work, but didn´t find a donate-link/ -button. Probably my fault....
Could you please tell me, where I could give a donation??

Anyways, thank you very much for giving us new content for the vive!!

**Comment by Codes4Fun** [comment]
I've setup a bounty source team page but they have not set it up yet, so it will be a while before I can accept donations (note their website seems kind of sluggish right now):
https://www.bountysource.com/teams/doom-3-bfg-openvr

Bounty Source accounts can be linked to your GitHub account (logging in to GitHub you can then login to Bounty Source). It also lets you put bounty rewards on issues you want to see resolved. I've actually received rewards in the past helping other open source projects such as OpenRA.

I also accept Bitcoins [17Mqj42oV1xtMWt16MBPyveZZXKUaJFH1H](https://blockchain.info/address/17Mqj42oV1xtMWt16MBPyveZZXKUaJFH1H), or if you just bought Bitcoins for yourself and saved them, that would increase the value of Bitcoin and we both benefit long term.

**Comment by Codes4Fun** [comment]
The site seems to be working now, so closing this out.

Thanks for the donation!
