### ISSUE TITLE
Under the floor

### ISSUE THREAD

**Issue by Antiquuus** [Codes4Fun/RBDOOM-3-BFG#47]
GTX 970
Intel i7 4790
Window 10
CV1
Doom3 BFG - no mods -Steam edition

I see at the level of the floor and I try to custom the sensor in Oculus Rift option but it is not working at all.
Just this game put me in the floor.

**Comment by Codes4Fun** [comment]
Have you done the SteamVR room setup yet?

I have not run the Oculus Rift for a while, I will check it out.

**Comment by Codes4Fun** [comment]
Also if you are playing in seated mode try in the console (pressing the ~ key):
vr_resetPose

if you are not in seated mode, try it anyway it might reset something in SteamVR.
