### ISSUE TITLE
Couldn't Load Default .CFG

### ISSUE THREAD

**Issue by tho4711** [Codes4Fun/RBDOOM-3-BFG#51]
Hi,

Cant load either RBDoom3BFG or the Fallback option, just get the following:

(using vive)

- Please help! I have ran the game a few times on normal desktop version and tried different versions of the programme (using 7 now), also forced the application to use the GTX1080.

QA Timing INIT: 000000ms
RBDOOM 3 BFG 1.1.0.1401 win-x86 Nov 21 2016 15:03:16
3500 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HTT
Winsock Initialized
Found interface: {5AD80D67-7FDD-415B-8382-64BB27281BB3} Realtek PCIe GBE Family Controller - 192.168.0.6/255.255.255.0
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Current search path:
C:\Users\JonnyT6\Saved Games\id Software\RBDOOM 3 BFG/base
E:\Steam\steamapps\common\DOOM 3 BFG Edition\RBDoom3BFG.1.1.0.OpenVR7.3/base
file system initialized.
--------------------------------------
Couldn't load default.cfg
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed

The config file says:

unbindall
bind "1" "_impulse0"
bind "2" "_impulse2"
bind "3" "_impulse3"
bind "4" "_impulse5"
bind "5" "_impulse6"
bind "6" "_impulse7"
bind "7" "_impulse8"
bind "8" "_impulse9"
bind "9" "_impulse10"
bind "TAB" "_impulse19"
bind "Q" "_impulse12"
bind "W" "_forward"
bind "E" "_use"
bind "R" "_impulse13"
bind "T" "clientMessageMode"
bind "Y" "clientMessageMode 1"
bind "LBRACKET" "_impulse15"
bind "RBRACKET" "_impulse14"
bind "ENTER" "_button2"
bind "LCTRL" "_attack"
bind "A" "_moveleft"
bind "S" "_back"
bind "D" "_moveright"
bind "F" "_impulse16"
bind "LSHIFT" "_speed"
bind "C" "_movedown"
bind "SLASH" "_impulse14"
bind "SPACE" "_moveup"
bind "F5" "savegame quick"
bind "F9" "loadgame quick"
bind "F12" "screenshot"
bind "UPARROW" "_forward"
bind "LEFTARROW" "_left"
bind "RIGHTARROW" "_right"
bind "DOWNARROW" "_back"
bind "PGDN" "_lookup"
bind "DEL" "_lookdown"
bind "MOUSE1" "_attack"
bind "MOUSE2" "_moveup"
bind "MWHEELDOWN" "_impulse14"
bind "MWHEELUP" "_impulse15"
set m_show_messages "1"
set s_volume_midi "8"
set s_volume_sound "8"
set g_weaponShadows "0"
set g_checkpoints "1"
set stereoRender_interOccularCentimeters "3.0"
set g_laserSightLength "250"
set g_laserSightWidth "2.0"
set ui_showGun "1"
set g_spectatorChat "0"
set g_xp_bind_run_once "1"
set g_gameReviewPause "10"
set g_countDown "15"
set g_fov "80"
set g_gunScale "1"
set g_gunZ "0"
set g_gunY "0"
set g_gunX "3"
set g_showBrass "1"
set g_showProjectilePct "0"
set g_showHud "1"
set g_showPlayerShadow "0"
set g_showcamerainfo "0"
set g_healthTakeLimit "25"
set g_healthTakeAmt "5"
set g_healthTakeTime "5"
set g_useDynamicProtection "1"
set g_armorProtectionMP "0.6"
set g_armorProtection "0.3"
set g_damageScale "1"
set g_leNightmare "0"
set g_roeNightmare "0"
set g_nightmare "0"
set g_decals "1"
set g_bloodEffects "1"
set g_projectileLights "1"
set g_muzzleFlash "1"
set si_flagDropTimeLimit "30"
set si_spectators "1"
set si_teamDamage "0"
set si_timeLimit "10"
set si_fragLimit "10"
set si_mode "-1"
set si_map "-1"
set aa_targetAimAssistEnable "0"
set net_voice "1"
set net_socksPassword ""
set net_socksUsername ""
set net_socksPort "1080"
set net_socksServer ""
set s_device "-1"
set s_meterPosition "100 100 20 200"
set s_meterTopTime "1000"
set s_showLevelMeter "0"
set s_subFraction "0.5"
set com_requireNonProductionSignIn "1"
set ui_autoReload "1"
set ui_autoSwitch "1"
set ui_skinIndex "0"
set saveGame_verbose "0"
set swf_debug "0"
set s_volume_dB "0"
set r_motionBlur "0"
set r_forceScreenWidthCentimeters "0"
set stereoRender_deGhost "0.05"
set stereoRender_swapEyes "0"
set stereoRender_enable "0"
set r_debugArrowStep "120"
set r_debugLineWidth "1"
set r_debugLineDepthTest "0"
set r_lightScale "3"
set r_skipShadows "0"
set r_skipBump "0"
set r_skipSpecular "0"
set r_skipNewAmbient "0"

**Comment by Codes4Fun** [comment]
default.cfg is part of the base game data, basically the game can't find that data. Make sure it can find your Doom 3 BFG's "base" folder, either by:

1) Copying the zip file contents to where your "Doom3BFG.exe" is located (which should have a "base" folder in it, with a default.cfg file in it), or
2) Copying the "base" folder to where you've unzipped the file, or
3) Copy the "base" folder to the saved game folder: "%userprofile%\Saved Games\id Software\RBDOOM 3 BFG"

**Comment by Codes4Fun** [comment]
Alternatively, you can tell the exe where the original game is located via command line, for example:

RBDoom3BFG.exe +set fs_basepath "C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition"

**Comment by tho4711** [comment]
Thank you for coming back to me so fast. 
It is sorted now, the problem was when I extracted the filed I used "7zip" and it created a folder within the Doom folder and there seemed to be communication issues (presumtion as I am not technical....at all)

After reinstalling and extracting using the standard windows software it appeared differently within the Doom folder with all the .exe files showing (3 of them). After clicking the correct one, boom the game works perfectly. 

Only problem is I was up until 2am playing and now fcked for work but that's not an issue you can help with.

Thanks again.

**Comment by Codes4Fun** [comment]
Good to hear (about it working, not about being fcked for work :))!

Once I get further in the project, I'll probably create an official installer for it.
