### ISSUE TITLE
How to go to "Alpha Labs"

### ISSUE THREAD

**Issue by VRFR3D** [Codes4Fun/RBDOOM-3-BFG#54]
This is my very best VR experienc so far - thank you very much !!!

But how to go to the Alpha Labs - Doom3 shows the Console and stops working ...

best regards VRFR3D

**Comment by Codes4Fun** [comment]
This is very likely that you are using with a texture pack mod, you probably need to start clean without the texture pack to get past that level.

I think some of these texture pack mods were designed for Doom 3, and they are not entirely compatible with the Doom 3 BFG edition and so not entirely compatible with our VR mod.

**Comment by VRFR3D** [comment]
I found this 

**Delete the "Models" and "Collision" folders inside "generated", and try loading the new level again.**

and it works for me .

Thank you very much !

**Comment by Codes4Fun** [comment]
cool :)
