### ISSUE TITLE
Fix and Improve Seated Mode

### ISSUE THREAD

**Issue by Codes4Fun** [Codes4Fun/RBDOOM-3-BFG#55]
From the conversation on issue #49 with manefit!

Add motion controller support to Seated Mode.

Add duck button to controllers, or add support for custom binding buttons.

Fix several other bugs with it, like height is now broken.

**Comment by manefit** [comment]
wow thanks this is amazing I haven't tested the new build yet not much time till Tuesday. keep up the good work.

**Comment by manefit** [comment]
log file 'qconsole.log' opened on Tue Dec 13 01:07:26 2016

]vr_logDevices

head  model "Oculus Rift CV1"
left  model "" axis k_eControllerAxis_Joystick
right model "" axis k_eControllerAxis_Joystick
--------- Game Map Shutdown ----------
WARNING: idClipModel::FreeTraceModel: tried to free uncached trace model
--------------------------------------
Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,  1392 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
   30 images loaded in   0.0 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
    7 sounds loaded in   0.1 seconds
----------------------------------------
--------- Game Map Shutdown ----------
--------------------------------------
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying window
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
Shutdown event system
--------------------------------------

**Comment by Codes4Fun** [comment]
Hey! Thanks, that info helps a lot! Especially I just found out my Touch is arriving Friday :/

I should be creating a new release soon, probably later today.

**Comment by manefit** [comment]
no problem I want to be as helpful as I can and u going to love the touch it's the best combo of motion control and traditional gamepad in the best ways

**Comment by Codes4Fun** [comment]
So I released my changes in [version 12](https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/tag/1.1.0-openvr12), you can rebind the controls either by typing this in the console:

unbindallvr
bind "VR_LEFT_AXIS" "_impulse16"
bind "VR_LEFT_A" "_moveup"
bind "VR_LEFT_MENU" "_impulse19"
bind "VR_LEFT_TRIGGER" "_speed"
bind "VR_LEFT_GRIP" "_impulse15"
bind "VR_RIGHT_AXIS" "_movedown"
bind "VR_RIGHT_A" "_impulse13"
bind "VR_RIGHT_TRIGGER" "_attack"
bind "VR_RIGHT_GRIP" "_impulse14"
vr_moveMode 0
vr_rightAxis 1
vr_seated 1

or go to this folder in windows explorer:
%userprofile%\Saved Games\id Software\RBDOOM 3 BFG\base

And use notepad to edit D3BFGVRConfig.cfg and copy/paste those lines to that file.

I think those controls are what you had in mind, if they are wrong let me know what you want changed.

There are limitations, I can't change the oculus buttons, one is used for Oculus Home and the other for SteamVR Dashboard, and the pause menu can't be changed currently either, Doom 3 didn't support this by default so I would need to make another round of changes to possibly make it configurable.

In the future I will probably make a lot of this automated, or that you simply download a certain build and it works without needing to do any of that.

**Comment by manefit** [comment]
nice thanks I had a busy week I won't get a chance to update and test till sunday. hope u got ur touch they r amazing

**Comment by X3roxx** [comment]
@Codes4Fun  I'm playing with a Wiimote Guncontroller at the moment which actually works very well if i set it to the seated mode but standing in the Room. Could you maybe make a different vr_aimlook mode which only stick the x-axis to the view and make the y-axis free moveable? As already mentioned in my other post, the best solution would be a free aim mode but im not sure how difficult this is to implement.

**Comment by manefit** [comment]
@X3roxx with the touch or vive wand u r free to aim where ever. it's just the button mapping that needs just a little refining on the touch but it's almost perfect, wel for me that is... @Codes4Fun I will get a chance to play a little later so i'll do a log again and post it hope it helps

**Comment by Codes4Fun** [comment]
You shouldn't have to do a log, but try out the controls and let me know if you had something else in mind.

**Comment by manefit** [comment]
@Codes4Fun did u get ur touch? i'm doing a clean install of the going to do a quick test before bed

**Comment by Codes4Fun** [comment]
Yeah, I got my Touch. Played with it all weekend long :) . But everything should work better with it.

**Comment by manefit** [comment]
do u plan to try modding any another game over to VR... u pretty much have the blue print with this and can refine it just a bit more. if u know anyone or if yourself is working on like gta5 online, crisis, skyrim even fallout just give us the controls u have now. it would be nice to follow their progress
