### ISSUE TITLE
Control Option Suggestion [Solved]

### ISSUE THREAD

**Issue by Wip3ou7** [Codes4Fun/RBDOOM-3-BFG#56]
Squeezing the left grip for the flashlight is very unintuitive to me. Can we have an option to have the Flashlight activated via the Trigger, and Jump moved to being activated by Clicking-In the Touch Pad? 99% of the time you want to move simulatenously while jumping anyway, so jumping by clicking in on the move pad makes perfect sense to me. Sprint can be moved to holding the Grip, I barely use it anyway - touching the edge of the touchpad moves you plenty quick imo.

Thanks!

**Comment by Codes4Fun** [comment]
I've just released a new build that lets you rebind buttons. In your case you would want to do something like this:

bind "VR_LEFT_TRIGGER" "_impulse16"
bind "VR_LEFT_GRIP" "_moveup"

**Comment by Wip3ou7** [comment]
Awesome thanks for the quick response! It's like you read my mind!! xD I'm going to try it right now.
