### ISSUE TITLE
Disable Laser Sight Option [Solved]

### ISSUE THREAD

**Issue by Wip3ou7** [Codes4Fun/RBDOOM-3-BFG#57]
Forgive me if thats already an option.

With that being said it would become more important to make sure the iron sites of the gun models are properly aligned with their axis of fire, but most of the weapons are fine with hip fire anyway.

**Comment by Wip3ou7** [comment]
Nevermind, I found a solution... You can alter the laser width, or make it entirely invisible with this command:

(for invisible)
set g_laserSightWidth 0.0001

(for realistic width)
set g_laserSightWidth 0.1

Enjoy

**Comment by Codes4Fun** [comment]
Thanks
