### ISSUE TITLE
Will not start anymore

### ISSUE THREAD

**Issue by X3roxx** [Codes4Fun/RBDOOM-3-BFG#59]
Hi,

i was able to start it via RBDoom3BFG.exe but suddenly it stopped working and i can't launch the game in VR Mode anymore.  Windows always say "RBDoom3BFG.exe stopped working" The original Doom3BFG.exe is still working without any problems.

Edit: I managed to get it working again ---> deleted all stuff from "my Savegames/idsoftware...but after a short session the game crashed while i push on the first display in the first elevator. 2 seconds no screen, then back to the main menu with the console tab open. Furthermore the original Doom3BFG.exe is not working anymore, so the other way around now.

**Comment by Codes4Fun** [comment]
Are you using any of the texture pack mods? Those have been known to cause it to exit to main menu + console. Usually it can be fixed by deleting a generated folders content, but it probably depends on the texture pack.

**Comment by X3roxx** [comment]
I installed the ultimate HD Mod and the VR Mod, thats all

**Comment by Codes4Fun** [comment]
So people fix this by going to the folder where you run the game and going to base/generated folder and deleting model and collision folders.

There could be cases where it can't be fixed this way and you need to run a clean install without the Ultimate HD mod.
