### ISSUE TITLE
Take my money!

### ISSUE THREAD

**Issue by leppermessiah1** [Codes4Fun/RBDOOM-3-BFG#62]
Thank you so much for your dedication to making DOOM 3 in VR a R.  Where do I insert dollar bills?

**Comment by Codes4Fun** [comment]
I keep forgetting to add it to my release pages but I have a [bounty source page](https://www.bountysource.com/teams/doom-3-bfg-openvr) and a [bitcoin address](https://blockchain.info/address/17Mqj42oV1xtMWt16MBPyveZZXKUaJFH1H).

Have a Happy Holidays! :)
