### ISSUE TITLE
crash in first elevator to what i assume is level 2

### ISSUE THREAD

**Issue by zombieshindig** [Codes4Fun/RBDOOM-3-BFG#63]
New user, fresh virgin install, running RBdoom from desktop shortcut not steam, no mods, no texture packs, just RBDOOM-3-BFG 1.1.0 openvr 12. crashes at elevator switch. tried a roll back as some have suggested to RB ver 7 when this problem last seemed to exist, didn't work, reinstalled a few times, tried multiple things...  running win 10, nvidia 1070, i7, 16gb ram etc... kinda dumbfounded as not many people seem to be reporting this in december- did i over look a fix somewhere?

**Comment by TorrqTB** [comment]
I am crashing as well.  Entering Alpha Labs is where I believe I am.
It starts loading the level, then takes me to > console, and shows the main menu,

**Comment by Codes4Fun** [comment]
You can try deleting "%userprofile%\Saved Games\id Software\RBDOOM 3 BFG"  and backup your save games in the folder if you don't want to lose them.

Also look for a "generated" folder, which may be where ever you ran RBdoom3bfg.exe from or under base, and try to delete that (maybe it is corrupted for some reason).

Even if you do a "clean reinstall" texture packs can leave extra data behind, and depending on how you set up the mod, a "clean reinstall" may still have stuff left over in a generated folder.

@zombieshindig If you have never ever installed a texture pack before then this is definitely strange, do you also get dropped to console or does it exit to windows?

**Comment by TorrqTB** [comment]
I deleted the "generated" folder, under the base directory as suggested.
The first time I loaded, none of the Vive buttons worked.
I quit and reloaded, and the game was working again, and I could finally progress to next level without crashing.

Thanks!
