### ISSUE TITLE
Level Hell not loading

### ISSUE THREAD

**Issue by Starlight07** [Codes4Fun/RBDOOM-3-BFG#67]
Hello! First of all awesome job I am having a blast with this game! So if I understand correctly the levels from Hell to the end are not available in VR? Thx! :)

**Comment by Codes4Fun** [comment]
They are. Usually level loading issues are because of texture pack/mod issues, are you using a texture pack?

You could try finding and deleting a folder called "generated", might fix this issue for you.

**Comment by Starlight07** [comment]
I already did! I am using this texture pack: 
Texture/Ultimate HD pack compiled by WildSide_VR.
So I am not sure what else to try so far I had zero issues.
Thank's for the response!

**Comment by Codes4Fun** [comment]
I would say do a clean reinstall without the texture pack then.

What is the download link to that texture pack? I can try and reproduce and maybe debug it.

**Comment by Starlight07** [comment]
Download the Texture/Ultimate HD pack compiled by WildSide_VR here https://mega.nz/#!68BUCDZS!PVv4gQSrrP0i6U0Huetqfn-WBXZvpMkDKB81F7_9b7o use download to browser option so you don't deal with the mega software alternative download http://uploaded.net/file/as02ygj0

There you go I am going to try a fresh install, Your feedback is really appreciated!

**Comment by Starlight07** [comment]
Fresh re-install no Texture pack unable to load Hell level.
2 questions:
1- Is there a way I can find the error in the console, so that would give a clue?
2- Is there a console command that could bring me directly to that level?

Thx!

**Comment by Codes4Fun** [comment]
I think if there is output, you need to have a debugger attached to see it, you might see it if you run rbdoom3bfg.exe from command line (cmd.exe or hold shift and right click in a folder and select "open command window here").

You can go into the Dev menu, and load levels from there, but if you have an autosave you probably want to back it up, loading levels can replace your autosave.

**Comment by Starlight07** [comment]
Curse on you! You sent me to HELL! All jokes aside I used the Dev menu to go directly there and it loaded, not sure If it's normal that all my equipment is gone, but that's a detail, i'll find it back. Thank You very much for the help but we still can't figure out why it doesn't want to load in the first place? Odd!

**Comment by Codes4Fun** [comment]
I wasn't able to reproduce the issue with the texture pack but I didn't do a complete play through. Texture packs can also corrupt save games, so maybe there wasn't something that occurred early on and saved in your game so, I won't be able to reproduce it.
