### ISSUE TITLE
vr_knockbackScale  has no effect

### ISSUE THREAD

**Issue by xorborgas** [Codes4Fun/RBDOOM-3-BFG#68]
Hi, I've been impressed by the mod so far, but I've run into an issue thats making it uncomfortable.  I'm not able to stop the knockback effect when getting shot.

Now, I know I should be able to enter "vr_knockbackScale 0" into the console, but no matter what I try it has no effect, I get knocked back the same from every enemy shot.  I've tried adding the command to autoexec.cfg as well to see if that might let it take effect, but no dice.  When I type it and hit enter, it doesn't give any message about an unknown command, and I've tried it enough times to know I'm not making a spelling mistake or something.

I'm really tearing my hair out trying to figure this out because outside of this its amazing, but with the knockback it's unplayable for me.  I don't know if theres something I'm completely missing or what.

**Comment by Codes4Fun** [comment]
If you enter "vr_knockbackScale" with out specifying a number, it will display it's current value.

Also you might need to be more specific on how to reproduce this, I tested it again and it is working, at least testing Zombie Melee and Imp Fireballs. I don't know if some other kinds of damage could have done knockback differently. Although I don't see how, maybe some other vr setting is overriding this, so it might help to know what other vr settings you are using.

**Comment by xorborgas** [comment]
Sure, sorry i should have included more details.  I installed doom3 bfg fresh, then I installed the high def texture pack and thats it.  Basically I followed the instructions I found here: https://www.reddit.com/r/Vive/comments/5e1cbp/allinone_doom_3_bfg_vr_mod_texture_pack_guide/
I think I initially installed version 1.1.0 10, and subsequently now 12. 

When I type just "vr_knockbackScale" it returns a value of 0, but the enemy specifically I've been testing over and over on is just a standard soldier shooting a pistol.  The pistol shot knocks me back regardless if i set it to 0 or 1.  I haven't tested it on other monsters to be honest as I've just been reloading the same save to test it out.   The only other variables I've changed has been the flashlight battery time and the vr_chibi value.

I wish I could say I've installed other VR mods or something, but its pretty much vanilla + texture pack +rbdoom3 1.1.0 12.

**Comment by Codes4Fun** [comment]
Okay, I found where those knockbacks were occurring and I changed it to scale with vr_knockbackScale and I rebuilt and pushed it out to the release page as: [RBDoom3BFG.1.1.0.OpenVR12.5.3b6d3fc.zip](https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/download/1.1.0-openvr12/RBDoom3BFG.1.1.0.OpenVR12.5.3b6d3fc.zip)

**Comment by xorborgas** [comment]
Wow thats  fantastic!  All credit in the world to you, you're an awesome developer.
