### ISSUE TITLE
Flashlight stopped working

### ISSUE THREAD

**Issue by Mige5** [Codes4Fun/RBDOOM-3-BFG#69]
Hey

So yeah, my flashlight no longer works after entering alpha labs? (if I load to a save state before that, its working fine, but can no longer turn it on when alpha labs is loaded)

**Comment by Codes4Fun** [comment]
That is extremely strange, this is the first time I have heard of this issue. Possibly a texture pack issue, are you using a HD texture pack? You could maybe try deleting the "generated" folder.

Does this also happen loading the alpha labs from the Dev menu?

**Comment by Mige5** [comment]
Yeah, loading the HD texture pack from here: https://www.reddit.com/r/Vive/comments/5e1cbp/allinone_doom_3_bfg_vr_mod_texture_pack_guide/

had to delete everything except "images" from "generated" folder to load alpha labs in the first place.

how do I load it through the dev menu?

PS. thx for fast reply :)

**Comment by Codes4Fun** [comment]
The dev menu is accessible from the main menu, should be the second to last button. Selecting it, you will see a list of levels, there should be some there for alpha labs.

Sometimes also texture packs can corrupt saved games, so even if you go straight to a level from the dev menu it may work but your saved game is what is corrupted, even if things seem to be working when loading a save it can also be some corruption that doesn't occur until later.

Another thing you can try is using a console cheat command to give you a flashlight if somehow you no longer have one:

give weapon_flashlight

**Comment by Mige5** [comment]
Actually I even tried starting a new game, and its not working. (only seems to work on the game I saved)

I have these in autoexec, could there be a problem here?
flashlight_batteryFlickerPercent ".10"	//Flickery animation for flashlight
flashlight_minActivatePercent    ".015"	//Longer time to simulate battery changes
flashlight_batteryChargeTimeMS "150000"	//Longer time to simulate battery changes
flashlight_batteryDrainTimeMS "-1"	//More realistic flashlight_batteryChargeTimeMS

**Comment by Mige5** [comment]
Definitely an issue there, removed the bottom 2 and it worked.. how should I setup the commands there to get infinite flashlight?

**Comment by Codes4Fun** [comment]
Erare had said that the last one on that list was all they needed:

https://github.com/Codes4Fun/RBDOOM-3-BFG/issues/35

So maybe its the combination of the other ones that is breaking it.

**Comment by Mige5** [comment]
Removed everything else but the last one, and not working.

- I used it through console on the earlier save, and it works. (thats what he probably did too, but shouldnt it be done through autoexec, wouldnt I otherwise need to do it again everytime I load a new level)

**Comment by Mige5** [comment]
Seems that this will work just as infinite as -1:
flashlight_batteryDrainTimeMS "999999999"

^but this will also work if added to autoexec :)

finally can continue with this game, which I have found to be the best VR experience yet.

**Comment by Codes4Fun** [comment]
I enabled the wiki page added your recommendation!
