### ISSUE TITLE
Tunnel view when walking

### ISSUE THREAD

**Issue by mikkissi** [Codes4Fun/RBDOOM-3-BFG#75]
When i dont move everything looks good but when i walk i see only 2m x 2m view. Rest of normal fov is black

**Comment by jckhng** [comment]
Hi mikkissi, 

Try entering this command in the console.

vr_comfortMode 0

This will turn off the tunnel view while moving. It is meant to reduce motion sickness. You can set it back to 1, 2, or 3 if you experience motion sickness.

1 - tunnel only
2 - slow motion only
3 - tunnel and slow motion

**Comment by mikkissi** [comment]
Thx!!!
