### ISSUE TITLE
Use floor position/orientation in steamVR to help with head calibration

### ISSUE THREAD

**Issue by ecaginicolau** [Codes4Fun/RBDOOM-3-BFG#8]
I'm unfamilliar with openVR but can't you ask for the floor position/orientation? This would remove the need to calibrate the head at the start of the game.
This is mostly an orientation issue: if your hmd is not perfectly horizontal when calibrating then the whole world will look like leaning.

**Comment by Codes4Fun** [comment]
I use correct data from OpenVR in standing mode (in seated mode I use OpenVRs position/orientation).

There should be no leaning issues, are you maybe confusing the opening cinematic? The opening cinematic has the camera tilted.

The other aspect to this, the initial HMD position affects the position of the shell, but there should be no tilting at all, it just tries and presents the shell in front of the HMD.

**Comment by ecaginicolau** [comment]
Ok, did you fix the issue lately? I clearly had it a few times at the
begining but now i'm trying to avoid it so i'm unsure. I'll test it later
today to be sure. Sorry if it's not a real issue.

2016-11-21 17:33 GMT+01:00 Codes4Fun notifications@github.com:

**Comment by ecaginicolau** [comment]
I couldn't reproduice the orientation issue. 
Maybe it was on an earlier build
sorry
