### ISSUE TITLE
Can you PLEASE mod DOOM (2016) to work in room scale like this one?

### ISSUE THREAD

**Issue by Aesop112** [Codes4Fun/RBDOOM-3-BFG#91]
Doom (2016) would be incredible if done the way you did this one!

**Comment by BielBdeLuna** [comment]
Unfortunately, fat chance pal unless they open-source their engine. 
You could demand them to open source it though.

**Comment by cybtachyon** [comment]
No updates in 25 days about a request to open-source latest engine, let's mark this as closed.
